import type { SerializableTheme } from './types';

// ── 6개 테마 정의 (100% JSON-serializable) ──

export const classicTheme: SerializableTheme = {
  id: 'classic',
  containerBg: 'min-h-screen bg-gradient-to-b from-amber-50 via-white to-amber-50',
  sectionPadding: 'py-8 md:py-12 px-6',
  contentMaxWidth: 'max-w-2xl mx-auto',
  galleryMaxWidth: 'max-w-4xl mx-auto',
  headingClass: 'text-xl md:text-2xl font-serif text-center text-gray-800 mb-8 md:mb-12',
  bodyText: 'text-sm md:text-base text-gray-700 leading-relaxed whitespace-pre-line',
  nameClass: 'text-2xl md:text-3xl font-serif text-gray-800 mb-3 md:mb-4',
  labelClass: 'text-xs md:text-sm text-amber-800 mb-3 md:mb-4 font-medium',
  cardClass: 'flex items-start gap-3 md:gap-4 p-4 md:p-6 bg-white rounded-lg shadow-sm border border-amber-100',
  accountCardClass: 'p-4 md:p-5 bg-white rounded-xl shadow-sm border border-amber-100',
  iconColor: 'text-amber-600',
  accentColor: 'text-amber-600 hover:text-amber-700',
  sideLabel: 'text-sm md:text-base text-amber-800 mb-3 font-semibold',
  phoneLinkClass: 'inline-flex items-center gap-2 text-sm text-gray-600 hover:text-amber-600 transition-colors py-2 px-3 -mx-3 min-h-[44px]',
  accountTypeLabel: 'text-xs text-slate-500 mb-2',
  accountName: 'text-sm md:text-base text-gray-800 font-medium mb-1',
  accountDetail: 'text-xs md:text-sm text-gray-600',
  accountHolder: 'text-xs text-gray-500',
  noticeBg: 'p-4 md:p-6 bg-amber-50 rounded-lg',
  mapInfoBg: 'mt-4 p-4 bg-amber-50/60 rounded-lg',
  transportCard: 'mt-4 p-4 bg-white rounded-lg border border-amber-100',
  sectionBg: { parents: 'bg-amber-50/30', gallery: 'bg-amber-50/30', rsvp: 'bg-amber-50/30' },
  greetingDecorTop: { type: 'emoji', emoji: '🌸', symbolClass: 'text-3xl md:text-4xl' },
  greetingDecorBottom: undefined,
  greetingMaxWidth: 'max-w-2xl w-full',
  greetingAlign: 'text-center',
  galleryGap: 'gap-3 md:gap-4',
  galleryItemClass: 'aspect-square overflow-hidden rounded-lg shadow-md cursor-pointer',
  galleryHover: 'hover:scale-110 transition-transform duration-300',
  galleryItemAnimation: { preset: 'fade-scale', staggerDelay: 0.1 },
  parentsGrid: 'grid md:grid-cols-2 gap-8 md:gap-12',
  groomAnimation: { preset: 'slide-x-left' },
  brideAnimation: { preset: 'slide-x-right' },
  accountsSpacing: 'space-y-6 md:space-y-8',
  accountCardsSpacing: 'space-y-3',
  cardLabelClass: 'font-medium text-sm md:text-base text-gray-800 mb-1 md:mb-2',
  cardValueClass: 'text-sm md:text-base text-gray-600',
  cardSubTextClass: 'text-xs md:text-sm text-gray-600',
  noticeTextClass: 'text-xs md:text-sm text-gray-600 whitespace-pre-line leading-relaxed',
  transportLabelClass: 'text-xs font-semibold text-gray-700 mb-2',
  transportTextClass: 'text-xs text-gray-600 leading-relaxed whitespace-pre-line',
  ceremonyDateLabel: '예식 일시',
  ceremonyVenueLabel: '예식 장소',
  mapVenueNameClass: 'text-sm font-medium text-gray-800',
  mapAddressClass: 'text-xs text-gray-600 mt-1',
  mapShowTel: true,
  sectionDivider: undefined,
  postCoverDivider: undefined,

  // D-Day 달력
  calendarAccentColor: 'bg-amber-600 text-white',
  calendarTodayColor: 'ring-2 ring-amber-300',
  calendarHeaderClass: 'text-sm font-serif text-gray-700',
  calendarDayClass: 'text-xs text-gray-600',
  countdownNumberClass: 'text-4xl font-serif text-amber-700',
  countdownLabelClass: 'text-xs text-gray-500',
  countdownUnitClass: 'text-[10px] text-gray-400',

  // RSVP 폼
  rsvpInputClass: 'border-amber-200 focus:ring-2 focus:ring-amber-500 focus:border-transparent',
  rsvpActiveClass: 'bg-amber-600 text-white',
  rsvpInactiveClass: 'bg-amber-50 text-amber-800 hover:bg-amber-100',
  rsvpSubmitClass: 'bg-amber-600 hover:bg-amber-700 text-white',

  cover: {
    layout: 'center',
    imageOverlay: 'bg-gradient-to-b from-transparent via-white/50 to-white',
    imageClass: 'opacity-40',
    topDecoration: { type: 'emoji', emoji: '✨', symbolClass: 'text-5xl md:text-6xl', className: 'mb-6' },
    labelText: 'Wedding Invitation',
    labelClass: 'font-serif text-xs md:text-sm tracking-[0.3em] text-amber-800 mb-6 md:mb-8 uppercase',
    nameClass: 'font-serif text-3xl md:text-4xl text-gray-800',
    nameDivider: 'ampersand',
    ampersandClass: 'text-xl md:text-2xl text-amber-600',
    dateClass: 'text-base md:text-lg text-gray-600',
    animation: { preset: 'slide-y', duration: 1, delay: 0.2 },
    motionClass: 'relative z-10 text-center px-6',
  },

  footer: {
    layout: 'centered',
    containerClass: 'py-8 md:py-12 px-6 text-center text-xs md:text-sm text-gray-500 border-t border-amber-100',
    linkClass: 'text-amber-600 hover:text-amber-700',
  },
};

export const modernTheme: SerializableTheme = {
  id: 'modern',
  containerBg: 'min-h-screen bg-zinc-50',
  sectionPadding: 'py-12 md:py-16 px-8 md:px-12',
  galleryLayout: 'grid-3',
  parentsLayout: 'stacked',
  parentsFullHeight: false,
  greetingLayout: 'left-aligned',
  ceremonyLayout: 'inline',
  sectionSpacing: 'spacious',
  contentMaxWidth: 'max-w-2xl',
  galleryMaxWidth: 'max-w-4xl',
  headingClass: 'text-xs tracking-[0.3em] text-emerald-600 uppercase mb-6',
  bodyText: 'text-base md:text-lg text-zinc-600 leading-relaxed whitespace-pre-line',
  nameClass: 'text-2xl md:text-3xl font-sans font-bold text-zinc-900 mb-3',
  labelClass: 'text-xs text-zinc-400 mb-2',
  cardClass: 'flex items-start gap-4',
  accountCardClass: 'py-4 border-b border-zinc-200',
  iconColor: 'text-emerald-500',
  accentColor: 'text-emerald-600 hover:text-emerald-700',
  sideLabel: 'text-sm font-semibold text-zinc-800 mb-4',
  phoneLinkClass: 'inline-flex items-center gap-2 text-sm text-zinc-500 hover:text-emerald-600 transition-colors py-2 min-h-[44px]',
  accountTypeLabel: 'text-xs text-zinc-400 mb-1',
  accountName: 'text-sm text-zinc-800 font-medium',
  accountDetail: 'text-sm text-zinc-500 mt-1',
  accountHolder: 'text-xs text-zinc-400 mt-0.5',
  noticeBg: 'border-l-2 border-emerald-400 pl-4',
  mapInfoBg: 'mt-6 space-y-2',
  transportCard: 'mt-6 p-4 bg-zinc-100 rounded-lg',
  sectionBg: { gallery: 'bg-zinc-100' },
  greetingDecorTop: { type: 'text-label', text: 'Greeting', className: 'text-xs tracking-[0.3em] text-emerald-600 uppercase mb-6' },
  greetingDecorBottom: undefined,
  greetingMaxWidth: 'max-w-2xl w-full',
  greetingAlign: '',
  galleryGap: 'gap-2',
  galleryItemClass: 'aspect-square overflow-hidden cursor-pointer',
  galleryHover: 'hover:scale-105 transition-transform duration-500',
  galleryItemAnimation: { preset: 'scale', staggerDelay: 0.08 },
  parentsGrid: 'grid md:grid-cols-2 gap-12',
  parentsHeading: { type: 'text-label', headingClass: 'text-xs tracking-[0.3em] text-emerald-600 uppercase mb-10' },
  groomAnimation: { preset: 'slide-x-left', duration: 0.5 },
  brideAnimation: { preset: 'slide-x-right', duration: 0.5 },
  accountsSpacing: 'space-y-8',
  accountCardsSpacing: 'space-y-3',
  cardLabelClass: 'text-xs text-zinc-400 uppercase tracking-wide mb-1',
  cardValueClass: 'text-base text-zinc-800',
  cardSubTextClass: 'text-sm text-zinc-500',
  noticeTextClass: 'text-sm text-zinc-500 whitespace-pre-line leading-relaxed',
  transportLabelClass: 'text-xs font-semibold text-zinc-700 mb-2',
  transportTextClass: 'text-sm text-zinc-600 whitespace-pre-line leading-relaxed',
  ceremonyHeading: { type: 'text-label', headingClass: 'text-xs tracking-[0.3em] text-emerald-600 uppercase mb-6' },
  ceremonyDateLabel: 'Date & Time',
  ceremonyVenueLabel: 'Location',
  mapVenueNameClass: 'text-base font-medium text-zinc-800',
  mapAddressClass: 'text-sm text-zinc-500',
  sectionDivider: { type: 'horizontal-line', color: 'bg-zinc-200', className: 'mx-8 md:mx-12' },
  postCoverDivider: { type: 'gradient-line', color: 'from-transparent via-emerald-500/40 to-transparent' },

  // D-Day 달력
  calendarAccentColor: 'bg-emerald-600 text-white',
  calendarTodayColor: 'ring-2 ring-emerald-300',
  calendarHeaderClass: 'text-sm font-medium text-zinc-700',
  calendarDayClass: 'text-xs text-zinc-500',
  countdownNumberClass: 'text-5xl font-bold text-zinc-900',
  countdownLabelClass: 'text-xs text-zinc-400 uppercase tracking-wider',
  countdownUnitClass: 'text-[10px] text-zinc-400',

  // RSVP 폼
  rsvpInputClass: 'border-zinc-200 focus:ring-2 focus:ring-emerald-500 focus:border-transparent',
  rsvpActiveClass: 'bg-emerald-600 text-white',
  rsvpInactiveClass: 'bg-zinc-100 text-zinc-600 hover:bg-zinc-200',
  rsvpSubmitClass: 'bg-emerald-600 hover:bg-emerald-700 text-white',

  galleryHeading: { type: 'text-label', headingClass: 'text-xs tracking-[0.3em] text-emerald-600 uppercase mb-10' },
  accountsHeading: { type: 'text-label', headingClass: 'text-xs tracking-[0.3em] text-emerald-600 uppercase mb-10' },
  mapHeading: { type: 'text-label', headingClass: 'text-xs tracking-[0.3em] text-emerald-600 uppercase mb-6' },

  cover: {
    layout: 'bottom-left',
    imageOverlay: 'bg-gradient-to-t from-zinc-900/80 via-zinc-900/30 to-transparent',
    fallbackBg: 'bg-gradient-to-br from-zinc-800 to-zinc-900',
    labelText: 'Wedding Invitation',
    labelClass: 'text-xs tracking-[0.4em] text-emerald-400 uppercase mb-4',
    nameClass: 'text-5xl md:text-7xl font-sans font-bold text-white leading-tight mb-2',
    nameDivider: 'lines-with-ampersand',
    ampersandClass: 'text-emerald-400 text-lg',
    nameDividerLineClass: 'w-12 bg-emerald-400',
    dateClass: 'text-sm text-zinc-300 space-y-1',
    venueClass: 'text-zinc-400',
    animation: { preset: 'slide-x-left', duration: 0.8, delay: 0.2 },
    motionClass: 'relative z-10 px-8 md:px-12 w-full',
  },

  footer: {
    layout: 'flex-between',
    containerClass: 'py-10 md:py-14 px-8 md:px-12 border-t border-zinc-200',
    linkClass: 'hover:text-emerald-600 transition-colors',
  },
};

export const minimalTheme: SerializableTheme = {
  id: 'minimal',
  containerBg: 'min-h-screen bg-white',
  sectionPadding: 'py-10 md:py-16 px-6',
  galleryLayout: 'single-column',
  parentsLayout: 'compact',
  parentsFullHeight: false,
  greetingLayout: 'quote-style',
  ceremonyLayout: 'centered',
  sectionSpacing: 'normal',
  contentMaxWidth: 'max-w-md mx-auto',
  galleryMaxWidth: 'max-w-3xl mx-auto',
  headingClass: 'text-[10px] tracking-[0.3em] text-stone-400 uppercase text-center mb-8 font-myeongjo',
  bodyText: 'text-sm md:text-base text-stone-500 leading-loose whitespace-pre-line tracking-wide font-myeongjo font-light',
  nameClass: 'text-xl font-myeongjo font-light tracking-[0.1em] text-stone-900 mb-3',
  labelClass: 'text-[10px] tracking-[0.3em] text-stone-400 uppercase mb-4',
  cardClass: 'text-center',
  accountCardClass: 'py-3',
  iconColor: 'text-stone-300',
  accentColor: 'text-stone-400 hover:text-stone-600',
  sideLabel: 'text-xs font-medium text-stone-700 mb-4 tracking-wide',
  phoneLinkClass: 'inline-flex items-center gap-1.5 text-xs text-stone-400 hover:text-stone-600 transition-colors py-2 min-h-[44px]',
  accountTypeLabel: 'text-[10px] text-stone-400 mb-1',
  accountName: 'text-xs text-stone-700',
  accountDetail: 'text-xs text-stone-400 mt-1',
  accountHolder: 'text-[10px] text-stone-300 mt-0.5',
  noticeBg: 'pt-6',
  mapInfoBg: 'mt-6 space-y-1',
  transportCard: 'mt-6 pt-6',
  sectionBg: {},
  greetingDecorTop: undefined,
  greetingDecorBottom: undefined,
  greetingMaxWidth: 'max-w-md w-full',
  greetingAlign: 'text-center',
  galleryGap: 'gap-1',
  galleryItemClass: 'aspect-square overflow-hidden cursor-pointer',
  galleryHover: 'hover:opacity-80 transition-opacity duration-300',
  galleryItemAnimation: { preset: 'fade', staggerDelay: 0.05 },
  parentsGrid: 'grid grid-cols-2 gap-12',
  parentsRoleLabel: true,
  parentsFamilyNameClass: 'text-xs text-stone-400 mb-2',
  groomAnimation: { preset: 'fade', duration: 0.6 },
  brideAnimation: { preset: 'fade', duration: 0.6, delay: 0.1 },
  accountsSpacing: 'space-y-10',
  accountCardsSpacing: 'space-y-4',
  accountsDivider: { type: 'horizontal-line', color: 'bg-stone-200', size: 'w-8', className: 'flex justify-center' },
  cardLabelClass: '',
  cardValueClass: 'text-sm text-stone-700 tracking-wide',
  cardSubTextClass: 'text-xs text-stone-400 tracking-wide',
  noticeTextClass: 'text-xs text-stone-400 whitespace-pre-line leading-relaxed tracking-wide',
  transportLabelClass: '',
  transportTextClass: 'text-xs text-stone-400 whitespace-pre-line leading-relaxed tracking-wide',
  ceremonyCentered: true,
  ceremonyDateLabel: 'Date & Time',
  ceremonyVenueLabel: 'Location',
  ceremonyNoticeDivider: { type: 'horizontal-line', color: 'bg-stone-200', size: 'w-8', className: 'flex justify-center mb-6' },
  mapVenueNameClass: 'text-sm text-stone-800 font-medium tracking-wide',
  mapAddressClass: 'text-xs text-stone-400 tracking-wide',
  transportTopDivider: { type: 'horizontal-line', color: 'bg-stone-200', size: 'w-8', className: 'flex justify-center mb-6' },
  sectionDivider: { type: 'vertical-line', color: 'bg-stone-200', size: 'h-12', className: 'py-4' },
  postCoverDivider: { type: 'vertical-line', color: 'bg-stone-200', size: 'h-12', className: 'py-4' },

  // D-Day 달력
  calendarAccentColor: 'bg-stone-800 text-white',
  calendarTodayColor: 'ring-1 ring-stone-300',
  calendarHeaderClass: 'text-[10px] tracking-[0.2em] text-stone-400 uppercase',
  calendarDayClass: 'text-[10px] text-stone-400',
  countdownNumberClass: 'text-5xl font-myeongjo font-light tracking-wide text-stone-800',
  countdownLabelClass: 'text-[10px] tracking-[0.2em] text-stone-400 uppercase',
  countdownUnitClass: 'text-[10px] text-stone-300',

  // RSVP 폼
  rsvpInputClass: 'border-stone-300 focus:ring-1 focus:ring-stone-900 focus:border-transparent',
  rsvpActiveClass: 'bg-zinc-900 text-white',
  rsvpInactiveClass: 'bg-stone-100 text-stone-500 hover:bg-stone-200',
  rsvpSubmitClass: 'bg-zinc-900 hover:bg-zinc-800 text-white',

  galleryHeading: { type: 'text-label', headingClass: 'text-[10px] tracking-[0.3em] text-stone-400 uppercase text-center mb-12' },
  accountsHeading: { type: 'text-label', headingClass: 'text-[10px] tracking-[0.3em] text-stone-400 uppercase mb-12' },
  mapHeading: { type: 'text-label', headingClass: 'text-[10px] tracking-[0.3em] text-stone-400 uppercase mb-8' },

  cover: {
    layout: 'center',
    imageClass: 'opacity-20 grayscale',
    labelText: 'Wedding Invitation',
    labelClass: 'text-[10px] tracking-[0.5em] text-stone-400 uppercase mb-16 font-myeongjo',
    nameClass: 'text-3xl md:text-4xl font-myeongjo font-light tracking-[0.15em] text-stone-900',
    nameDivider: 'lines-only',
    nameDividerLineClass: 'w-16 bg-stone-300',
    dateClass: 'text-xs tracking-[0.2em] text-stone-400',
    venueClass: 'text-xs tracking-[0.2em] text-stone-400 mt-4',
    nameWrapperClass: 'space-y-6 mb-16',
    animation: { preset: 'fade', duration: 1.2, delay: 0.3 },
    motionClass: 'relative z-10 text-center px-6',
  },

  footer: {
    layout: 'centered',
    topDivider: { type: 'horizontal-line', color: 'bg-stone-200', size: 'w-8', className: 'flex justify-center mb-8' },
    containerClass: 'py-12 md:py-16 px-6 text-center',
    nameClass: 'text-[10px] tracking-[0.3em] text-stone-300',
    linkClass: 'text-[10px] tracking-[0.2em] text-stone-300 hover:text-stone-500 transition-colors',
  },
};

export const floralTheme: SerializableTheme = {
  id: 'floral',
  containerBg: 'min-h-screen bg-gradient-to-b from-rose-50 via-pink-50/30 to-rose-50',
  sectionPadding: 'py-8 md:py-12 px-6',
  galleryLayout: 'masonry',
  parentsLayout: 'cards',
  parentsFullHeight: true,
  ceremonyLayout: 'cards',
  sectionSpacing: 'normal',
  contentMaxWidth: 'max-w-lg mx-auto',
  galleryMaxWidth: 'max-w-4xl mx-auto',
  headingClass: 'font-batang text-xl text-center text-rose-800 mb-10',
  bodyText: 'font-batang text-sm md:text-base text-rose-800/70 leading-relaxed whitespace-pre-line',
  nameClass: 'font-batang text-2xl text-rose-900 mb-3',
  labelClass: 'text-xs text-rose-400 mb-3',
  cardClass: 'flex items-start gap-4 p-5 bg-white/60 rounded-2xl border border-rose-100',
  accountCardClass: 'p-4 bg-white/60 rounded-2xl border border-rose-100 text-center',
  iconColor: 'text-rose-400',
  accentColor: 'text-rose-400 hover:text-rose-600',
  sideLabel: 'text-sm text-rose-600 mb-3 font-semibold text-center',
  phoneLinkClass: 'inline-flex items-center gap-1.5 text-xs text-rose-400 hover:text-rose-600 transition-colors py-2 min-h-[44px]',
  accountTypeLabel: 'text-[10px] text-rose-400 mb-1',
  accountName: 'text-sm text-rose-900 font-medium',
  accountDetail: 'text-xs text-rose-500/70 mt-1',
  accountHolder: 'text-[10px] text-rose-400 mt-0.5',
  noticeBg: 'p-5 bg-pink-50/60 rounded-2xl border border-rose-100',
  mapInfoBg: 'mt-6 p-4 bg-white/60 rounded-2xl border border-rose-100 text-center',
  transportCard: 'mt-4 p-5 bg-pink-50/60 rounded-2xl border border-rose-100',
  sectionBg: { rsvp: 'bg-rose-50/30' },
  greetingDecorTop: { type: 'symbol-with-lines', symbol: '\u2740', lineColor: 'to-rose-200', lineSize: 'w-12', symbolClass: 'text-rose-300 text-lg mx-3' },
  greetingDecorBottom: { type: 'symbol-with-lines', symbol: '\u2740', lineColor: 'to-rose-200', lineSize: 'w-12', symbolClass: 'text-rose-300 text-lg mx-3' },
  greetingMaxWidth: 'max-w-lg w-full',
  greetingAlign: 'text-center',
  galleryGap: 'gap-3',
  galleryItemClass: 'aspect-square overflow-hidden rounded-2xl shadow-sm cursor-pointer border border-rose-100',
  galleryHover: 'hover:scale-110 transition-transform duration-300',
  galleryItemAnimation: { preset: 'fade-scale', staggerDelay: 0.08 },
  parentsGrid: 'grid md:grid-cols-2 gap-8',
  parentsCardWrapper: 'text-center bg-white/50 rounded-2xl p-6 border border-rose-100',
  groomAnimation: { preset: 'scale', duration: 0.5 },
  brideAnimation: { preset: 'scale', duration: 0.5, delay: 0.1 },
  accountsSpacing: 'space-y-6',
  accountCardsSpacing: 'space-y-3',
  cardLabelClass: 'font-batang text-sm text-rose-800 mb-1',
  cardValueClass: 'text-sm text-rose-600/70',
  cardSubTextClass: 'text-xs text-rose-500/70',
  noticeTextClass: 'text-xs text-rose-500/70 whitespace-pre-line leading-relaxed',
  transportLabelClass: 'text-xs font-semibold text-rose-700 mb-2',
  transportTextClass: 'text-xs text-rose-500/70 whitespace-pre-line leading-relaxed',
  ceremonyDateLabel: '예식 일시',
  ceremonyVenueLabel: '예식 장소',
  mapVenueNameClass: 'text-sm text-rose-800 font-medium',
  mapAddressClass: 'text-xs text-rose-500/70 mt-1',
  sectionDivider: undefined,
  postCoverDivider: undefined,

  // D-Day 달력
  calendarAccentColor: 'bg-rose-500 text-white',
  calendarTodayColor: 'ring-2 ring-rose-200',
  calendarHeaderClass: 'text-sm font-batang text-rose-700',
  calendarDayClass: 'text-xs text-rose-400',
  countdownNumberClass: 'text-4xl font-batang text-rose-700',
  countdownLabelClass: 'text-xs text-rose-400',
  countdownUnitClass: 'text-[10px] text-rose-300',

  // RSVP 폼
  rsvpInputClass: 'border-rose-200 focus:ring-2 focus:ring-rose-400 focus:border-transparent',
  rsvpActiveClass: 'bg-rose-500 text-white',
  rsvpInactiveClass: 'bg-rose-50 text-rose-700 hover:bg-rose-100',
  rsvpSubmitClass: 'bg-rose-500 hover:bg-rose-600 text-white',

  mapHeading: { type: 'text-label', lineColor: 'to-rose-200', lineSize: 'w-12', headingClass: 'font-batang text-xl text-rose-800', className: 'flex items-center justify-center gap-3 mb-8' },

  cover: {
    layout: 'center',
    imageOverlay: 'bg-gradient-to-b from-rose-50/60 via-transparent to-rose-50',
    imageClass: 'opacity-30',
    topDecoration: { type: 'emoji', emoji: '\u{1F33A}', symbolClass: 'text-3xl opacity-60', className: 'mb-4' },
    bottomDecoration: { type: 'emoji', emoji: '\u{1F338}', symbolClass: 'text-3xl opacity-60', className: 'mt-8' },
    labelText: 'Wedding Invitation',
    labelClass: 'font-batang text-xs tracking-[0.3em] text-rose-400 mb-8',
    nameWrapperClass: 'inline-block bg-white/60 backdrop-blur-sm rounded-3xl px-10 py-8 shadow-sm border border-rose-100',
    nameClass: 'font-batang text-3xl md:text-4xl text-rose-900',
    nameDivider: 'ampersand',
    ampersandClass: 'text-rose-300 text-lg',
    dateClass: 'text-sm text-rose-500',
    venueClass: 'text-sm text-rose-400 mt-3',
    animation: { preset: 'slide-y', duration: 1, delay: 0.2 },
    motionClass: 'relative z-10 text-center px-6',
  },

  footer: {
    layout: 'centered',
    topDecoration: { type: 'symbol-with-lines', symbol: '\u2740', lineColor: 'to-rose-200', lineSize: 'w-8', symbolClass: 'text-rose-300 text-sm mx-3', className: 'flex items-center justify-center mb-6' },
    containerClass: 'py-10 md:py-14 px-6 text-center',
    nameClass: 'text-xs text-rose-400',
    linkClass: 'text-xs text-rose-300 hover:text-rose-500 transition-colors',
  },
};

export const elegantTheme: SerializableTheme = {
  id: 'elegant',
  containerBg: 'min-h-screen bg-gradient-to-b from-amber-50/30 via-white to-slate-50',
  sectionPadding: 'py-12 md:py-16 px-6',
  galleryLayout: 'grid-2-1',
  parentsFullHeight: true,
  ceremonyLayout: 'timeline',
  sectionSpacing: 'spacious',
  contentMaxWidth: 'max-w-2xl mx-auto',
  galleryMaxWidth: 'max-w-4xl mx-auto',
  headingClass: 'text-xl md:text-2xl font-serif text-center text-slate-800 mb-8 md:mb-12',
  bodyText: 'text-sm md:text-base text-slate-600 leading-relaxed whitespace-pre-line font-light',
  nameClass: 'text-2xl md:text-3xl font-serif text-white mb-3',
  labelClass: 'text-xs tracking-[0.3em] text-amber-400/80 uppercase mb-4',
  cardClass: 'flex items-start gap-4 p-6 bg-white rounded-lg border border-slate-200 shadow-sm',
  accountCardClass: 'p-4 bg-white rounded-lg border border-slate-200 text-center',
  iconColor: 'text-amber-500',
  accentColor: 'text-amber-600 hover:text-amber-700',
  sideLabel: 'text-sm font-semibold text-slate-700 mb-4 text-center',
  phoneLinkClass: 'inline-flex items-center gap-2 text-sm text-slate-400 hover:text-amber-400 transition-colors py-2 min-h-[44px]',
  accountTypeLabel: 'text-xs text-slate-400 mb-1',
  accountName: 'text-sm font-medium text-slate-800',
  accountDetail: 'text-sm text-slate-500 mt-1',
  accountHolder: 'text-xs text-slate-400 mt-0.5',
  noticeBg: 'p-6 bg-amber-50/50 rounded-lg border border-amber-100',
  mapInfoBg: 'mt-6 p-4 bg-white rounded-lg border border-slate-200 text-center',
  transportCard: 'mt-4 p-4 bg-white rounded-lg border border-slate-200',
  sectionBg: { parents: 'bg-slate-800', gallery: 'bg-slate-800', map: 'bg-slate-50', rsvp: 'bg-slate-50' },
  greetingDecorTop: { type: 'diamond-with-lines', lineColor: 'to-amber-400/60', lineSize: 'w-16', symbolClass: 'w-2 h-2 rotate-45 border border-amber-400/60 mx-4' },
  greetingDecorBottom: { type: 'diamond-with-lines', lineColor: 'to-amber-400/60', lineSize: 'w-16', symbolClass: 'w-2 h-2 rotate-45 border border-amber-400/60 mx-4' },
  greetingMaxWidth: 'max-w-2xl w-full',
  greetingAlign: 'text-center',
  galleryGap: 'gap-3',
  galleryItemClass: 'aspect-square overflow-hidden rounded-lg cursor-pointer',
  galleryHover: 'hover:scale-110 transition-transform duration-500',
  galleryItemAnimation: { preset: 'scale', staggerDelay: 0.08 },
  parentsGrid: 'grid md:grid-cols-2 gap-10',
  parentsRoleLabel: true,
  parentsFamilyNameClass: 'text-xs text-slate-400 mb-2',
  groomAnimation: { preset: 'slide-y' },
  brideAnimation: { preset: 'slide-y', delay: 0.1 },
  accountsSpacing: 'space-y-8',
  accountCardsSpacing: 'space-y-3',
  cardLabelClass: 'text-xs tracking-[0.2em] text-slate-400 uppercase mb-2',
  cardValueClass: 'text-base text-slate-800',
  cardSubTextClass: 'text-sm text-slate-500',
  noticeTextClass: 'text-sm text-slate-600 whitespace-pre-line leading-relaxed',
  transportLabelClass: 'text-xs font-semibold text-slate-700 mb-2',
  transportTextClass: 'text-sm text-slate-600 leading-relaxed whitespace-pre-line',
  ceremonyDateLabel: 'Date & Time',
  ceremonyVenueLabel: 'Location',
  mapVenueNameClass: 'text-base font-medium text-slate-800',
  mapAddressClass: 'text-sm text-slate-500 mt-1',
  sectionDivider: undefined,
  postCoverDivider: undefined,

  // D-Day 달력
  calendarAccentColor: 'bg-amber-500 text-white',
  calendarTodayColor: 'ring-2 ring-amber-300',
  calendarHeaderClass: 'text-xs tracking-[0.2em] text-slate-500 uppercase',
  calendarDayClass: 'text-xs text-slate-500',
  countdownNumberClass: 'text-5xl font-serif text-slate-800',
  countdownLabelClass: 'text-xs tracking-[0.2em] text-amber-500 uppercase',
  countdownUnitClass: 'text-[10px] text-slate-400',

  // RSVP 폼
  rsvpInputClass: 'border-slate-200 focus:ring-2 focus:ring-amber-500 focus:border-transparent',
  rsvpActiveClass: 'bg-amber-500 text-white',
  rsvpInactiveClass: 'bg-slate-100 text-slate-600 hover:bg-slate-200',
  rsvpSubmitClass: 'bg-amber-600 hover:bg-amber-700 text-white',

  galleryHeading: { type: 'with-sub-label', subLabel: 'Moments', subLabelClass: 'text-xs tracking-[0.3em] text-amber-500 uppercase mb-2', headingClass: 'text-xl md:text-2xl font-serif text-slate-800', className: 'text-center mb-10' },
  accountsHeading: { type: 'with-sub-label', subLabel: 'Gift', subLabelClass: 'text-xs tracking-[0.3em] text-amber-500 uppercase mb-2', headingClass: 'text-xl md:text-2xl font-serif text-slate-800', className: 'text-center mb-10' },
  mapHeading: { type: 'with-sub-label', subLabel: 'Location', subLabelClass: 'text-xs tracking-[0.3em] text-amber-500 uppercase mb-2', headingClass: 'text-xl md:text-2xl font-serif text-slate-800', className: 'text-center mb-10' },

  cover: {
    layout: 'center',
    imageOverlay: 'bg-gradient-to-b from-slate-900/20 via-transparent to-white',
    imageClass: 'opacity-30',
    topDecoration: { type: 'diamond-with-lines', lineColor: 'to-amber-400', lineSize: 'w-12', symbolClass: 'w-3 h-3 rotate-45 border-2 border-amber-400 mx-3', className: 'flex items-center justify-center mb-8' },
    bottomDecoration: { type: 'diamond-with-lines', lineColor: 'to-amber-400', lineSize: 'w-12', symbolClass: 'w-3 h-3 rotate-45 border-2 border-amber-400 mx-3', className: 'flex items-center justify-center mb-8' },
    labelText: 'Wedding Invitation',
    labelClass: 'text-xs tracking-[0.4em] text-amber-600 uppercase mb-8',
    nameClass: 'font-serif text-4xl md:text-5xl text-slate-800',
    nameWrapperClass: 'space-y-4 mb-10',
    nameDivider: 'ampersand',
    ampersandClass: 'text-2xl text-amber-500 font-light',
    dateClass: 'text-sm tracking-wide text-slate-600',
    venueClass: 'text-sm tracking-wide text-slate-600 mt-4',
    animation: { preset: 'slide-y', duration: 1, delay: 0.2 },
    motionClass: 'relative z-10 text-center px-6',
  },

  footer: {
    layout: 'centered',
    topDecoration: { type: 'diamond-with-lines', lineColor: 'to-amber-400/40', lineSize: 'w-8', symbolClass: 'w-2 h-2 rotate-45 border border-amber-400/40 mx-3', className: 'flex items-center justify-center mb-4' },
    containerClass: 'py-10 md:py-14 px-6 text-center bg-slate-800',
    nameClass: 'text-sm text-slate-400',
    linkClass: 'text-xs text-slate-500 hover:text-amber-400 transition-colors',
  },
};

export const naturalTheme: SerializableTheme = {
  id: 'natural',
  containerBg: 'min-h-screen bg-gradient-to-b from-stone-50 via-emerald-50/20 to-stone-50',
  sectionPadding: 'py-10 md:py-16 px-6',
  galleryLayout: 'grid-2',
  parentsLayout: 'cards',
  parentsFullHeight: false,
  sectionSpacing: 'normal',
  contentMaxWidth: 'max-w-2xl mx-auto',
  galleryMaxWidth: 'max-w-4xl mx-auto',
  headingClass: 'text-xl md:text-2xl font-batang font-light text-center text-stone-800 mb-8 md:mb-12',
  bodyText: 'text-sm md:text-base text-stone-600 leading-loose whitespace-pre-line',
  nameClass: 'text-2xl md:text-3xl font-batang font-light text-stone-800 mb-3',
  labelClass: 'text-xs tracking-[0.2em] text-emerald-600/70 uppercase mb-3',
  cardClass: 'flex items-start gap-4 p-6 bg-white rounded-2xl border border-emerald-100 shadow-sm',
  accountCardClass: 'p-4 bg-white/80 rounded-2xl border border-emerald-100 text-center',
  iconColor: 'text-emerald-500',
  accentColor: 'text-emerald-600 hover:text-emerald-700',
  sideLabel: 'text-sm font-medium text-emerald-700 mb-4 text-center',
  phoneLinkClass: 'inline-flex items-center gap-2 text-sm text-stone-500 hover:text-emerald-600 transition-colors py-2 min-h-[44px]',
  accountTypeLabel: 'text-xs text-stone-400 mb-1',
  accountName: 'text-sm font-medium text-stone-800',
  accountDetail: 'text-sm text-stone-500 mt-1',
  accountHolder: 'text-xs text-stone-400 mt-0.5',
  noticeBg: 'p-6 bg-emerald-50/50 rounded-2xl border border-emerald-100',
  mapInfoBg: 'mt-6 p-4 bg-white/80 rounded-2xl border border-emerald-100 text-center',
  transportCard: 'mt-4 p-4 bg-white/80 rounded-2xl border border-emerald-100',
  sectionBg: { parents: 'bg-emerald-50/30', accounts: 'bg-emerald-50/30', map: 'bg-emerald-50/30' },
  greetingDecorTop: { type: 'emoji', emoji: '\u{1F33F}', symbolClass: 'text-xl opacity-60' },
  greetingDecorBottom: { type: 'emoji', emoji: '\u{1F33F}', symbolClass: 'text-xl opacity-60' },
  greetingMaxWidth: 'max-w-2xl w-full',
  greetingAlign: 'text-center',
  galleryGap: 'gap-4',
  galleryItemClass: 'aspect-square overflow-hidden rounded-2xl cursor-pointer shadow-sm',
  galleryHover: 'hover:scale-105 transition-transform duration-500',
  galleryItemAnimation: { preset: 'slide-y', staggerDelay: 0.08 },
  parentsGrid: 'grid md:grid-cols-2 gap-10',
  parentsCardWrapper: 'text-center p-6 bg-white/60 rounded-2xl',
  parentsRoleLabel: true,
  parentsFamilyNameClass: 'text-xs text-stone-400 mb-2',
  groomAnimation: { preset: 'slide-x-left' },
  brideAnimation: { preset: 'slide-x-right' },
  accountsSpacing: 'space-y-8',
  accountCardsSpacing: 'space-y-3',
  cardLabelClass: 'text-xs tracking-[0.15em] text-emerald-600/70 uppercase mb-2',
  cardValueClass: 'text-base text-stone-700',
  cardSubTextClass: 'text-sm text-stone-500',
  noticeTextClass: 'text-sm text-stone-600 whitespace-pre-line leading-relaxed',
  transportLabelClass: 'text-xs font-semibold text-stone-700 mb-2',
  transportTextClass: 'text-sm text-stone-600 leading-relaxed whitespace-pre-line',
  ceremonyDateLabel: 'Date & Time',
  ceremonyVenueLabel: 'Location',
  mapVenueNameClass: 'text-base font-medium text-stone-800',
  mapAddressClass: 'text-sm text-stone-500 mt-1',
  sectionDivider: undefined,
  postCoverDivider: undefined,

  // D-Day 달력
  calendarAccentColor: 'bg-emerald-500 text-white',
  calendarTodayColor: 'ring-2 ring-emerald-200',
  calendarHeaderClass: 'text-sm font-light text-stone-600',
  calendarDayClass: 'text-xs text-stone-500',
  countdownNumberClass: 'text-4xl font-light text-stone-800',
  countdownLabelClass: 'text-xs tracking-[0.15em] text-emerald-600/70 uppercase',
  countdownUnitClass: 'text-[10px] text-stone-400',

  // RSVP 폼
  rsvpInputClass: 'border-emerald-200 focus:ring-2 focus:ring-emerald-400 focus:border-transparent',
  rsvpActiveClass: 'bg-emerald-500 text-white',
  rsvpInactiveClass: 'bg-stone-100 text-stone-600 hover:bg-stone-200',
  rsvpSubmitClass: 'bg-emerald-500 hover:bg-emerald-600 text-white',

  galleryHeading: { type: 'with-decoration', decoration: '\u{1F33F}', decorationClass: 'text-2xl opacity-60', headingClass: 'text-xl md:text-2xl font-light text-stone-800 mt-2', className: 'text-center mb-10' },
  accountsHeading: { type: 'with-decoration', decoration: '\u{1F33F}', decorationClass: 'text-2xl opacity-60', headingClass: 'text-xl md:text-2xl font-light text-stone-800 mt-2', className: 'text-center mb-10' },
  mapHeading: { type: 'with-decoration', decoration: '\u{1F33F}', decorationClass: 'text-2xl opacity-60', headingClass: 'text-xl md:text-2xl font-light text-stone-800 mt-2', className: 'text-center mb-10' },

  cover: {
    layout: 'center',
    imageOverlay: 'bg-gradient-to-b from-stone-50/50 via-transparent to-stone-50',
    imageClass: 'opacity-40',
    topDecoration: { type: 'emoji', emoji: '\u{1F343}', symbolClass: 'text-4xl opacity-40', className: 'mb-4' },
    bottomDecoration: { type: 'emoji', emoji: '\u{1F33F}', symbolClass: 'text-4xl opacity-40', className: 'mt-8' },
    labelText: 'Wedding Invitation',
    labelClass: 'text-xs tracking-[0.4em] text-emerald-600/80 uppercase mb-8',
    nameClass: 'font-batang font-light text-4xl md:text-5xl text-stone-800 tracking-wide',
    nameWrapperClass: 'space-y-4 mb-8',
    nameDivider: 'lines-with-ampersand',
    ampersandClass: 'text-emerald-500/70 text-lg',
    nameDividerLineClass: 'w-8 bg-emerald-400/50',
    dateClass: 'text-sm text-stone-500',
    venueClass: 'text-sm text-stone-500 mt-4',
    animation: { preset: 'slide-y', duration: 1, delay: 0.2 },
    motionClass: 'relative z-10 text-center px-6',
  },

  footer: {
    layout: 'centered',
    topDecoration: { type: 'emoji', emoji: '\u{1F33F}', symbolClass: 'text-lg opacity-40', className: 'flex items-center justify-center gap-2 mb-4' },
    containerClass: 'py-10 md:py-14 px-6 text-center',
    nameClass: 'text-sm text-stone-500',
    linkClass: 'text-xs text-stone-400 hover:text-emerald-600 transition-colors',
  },
};

// ── 테마 레지스트리 ──

export const themes: Record<string, SerializableTheme> = {
  classic: classicTheme,
  modern: modernTheme,
  minimal: minimalTheme,
  floral: floralTheme,
  elegant: elegantTheme,
  natural: naturalTheme,
};

export function getTheme(templateId: string): SerializableTheme {
  return themes[templateId] ?? classicTheme;
}
